[project]
name = "albert-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "feedparser>=6.0.12",
    "mcp[cli]>=1.14.1",
    "requests>=2.32.5",
]

[project.scripts]
albert-mcp-server = "server:main"
